### ISSUE TITLE
Please migrate to trilium 0.48

### ISSUE THREAD

**Issue by regomne** [Nriver/NieR-Automata-Trilium-Theme#1]
Thanks!

**Comment by Nriver** [comment]
I've made some rough modification for 0.48, you can try it.

![ksnip_20211126-155442](https://user-images.githubusercontent.com/6752679/143546413-7d02af61-ebeb-4f41-b061-a1c24e67eada.png)

**Comment by regomne** [comment]
It works, thank you!
