### ISSUE TITLE
Cannot install this theme

### ISSUE THREAD

**Issue by Anoly-Mous** [Nriver/NieR-Automata-Trilium-Theme#2]
Hi! That looks amazing but I cannot understand how exactly I can install this theme on Mac - I see a couple folders and tried to unzip/ add zip achieve to every folder but nothing happened. I check this theme in "Appearance". 

Could you please explain little bit deeply how to setup this theme on Mac?

**Comment by Nriver** [comment]
Right click on the note tree. Click `import note` and choose the zip file. Restart Trilium and you should be able to see the theme in options.
